spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/findfood
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    port: 587
    username: root
    password: root
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
